### ISSUE TITLE
UE4 Virtual Texture

### ISSUE THREAD

**Issue by papalqi** [UnrealCommunity/commit_wiki#1]
external:
  -
    title: UE4 Virtual Texture
    link: https://zhuanlan.zhihu.com/p/373969159
    describtion: UE4 Virtual Texture 源码解析
    categories:
      - Rendering
      - Virtual Texture
    tags:
      - Rendering
      - 源码解析
  -
    title: UE4 Niagara源码解析
    link: https://zhuanlan.zhihu.com/p/362638250
    categories:
      - 特效粒子
      - Niagara
    tags:
      - Niagara
      - 源码解析
  -
    title: UE4 Chaos框架解析
    link: https://zhuanlan.zhihu.com/p/342638827
    categories:
      - 物理系统
    tags:
      - Chaos
      - 源码解析

**Comment by hxhb** [comment]
nice，三篇都已添加，给你的github发送权限邀请了。

**Comment by hxhb** [comment]
感谢你提交的文章。我新加了一个提交外部平台文章的issues模板，后续用这个格式提交就可以：

![](https://img.imzlp.com/imgs/zlp/picgo/2021/20211107122447.png)

使用md的table：

| 文章名 | 文章链接 | 发表时间 | 分类(`/`分隔) | 标签(`/`分隔) | 作者名 | GithubID | Email | Website |AvatarLink |
|-------|----------|---------|--------------|---------------|-------|----------|-------|---------|-----------|
|       |          |         |              |               |       |          |       |         |           |

已提交的外部平台文章如果URL有变化可以通过编辑这个页面修改：[elinks/table](https://ue5wiki.com/elinks/table)

**Comment by papalqi** [comment]
> 感谢你提交的文章。我新加了一个提交外部平台文章的issues模板，后续用这个格式提交就可以：
> 
> ![](https://camo.githubusercontent.com/bcb0d0d373b07b192076540cc0d75f6da16e31fa92459246d34cc79290a1f5d8/68747470733a2f2f696d672e696d7a6c702e636f6d2f696d67732f7a6c702f706963676f2f323032312f32303231313130373132323434372e706e67)
> 
> 使用md的table：
> 
> 文章名	文章链接	发表时间	分类(`/`分隔)	标签(`/`分隔)	作者名	GithubID	Email	Website	AvatarLink
> 已提交的外部平台文章如果URL有变化可以通过编辑这个页面修改：[elinks/table](https://ue5wiki.com/elinks/table)

好的，感谢~

**Comment by papalqi** [comment]
请问如何做本地测试呢

**Comment by hxhb** [comment]
> 请问如何做本地测试呢

完整的站点部署，依赖hexo和[ue5wiki_site](https://github.com/UnrealCommunity/ue5wiki_site)和[ue5wiki_source](https://github.com/UnrealCommunity/ue5wiki_source)这两个仓库，我在github上部署了actions，更改source之后会自动触发生成。
