### ISSUE TITLE
外部文章收录

### ISSUE THREAD

**Issue by BA3000** [UnrealCommunity/commit_wiki#4]
| 文章名 | 文章链接 | 发表时间 | 分类(`/`分隔) | 标签(`/`分隔) | 作者名 | GithubID | Email | Website |AvatarLink |
|-------|----------|---------|--------------|---------------|-------|----------|-------|---------|-----------|
|  UE4技术总结——委托     |    https://www.cnblogs.com/yejianying/p/ue4_note_delegate.html      |    2021/10/08    |    Engine    |  Delegate    |   SRIN   |  BA3000  |    wubrightarmy@outlook.com     |     https://www.cnblogs.com/yejianying/      |  https://avatars.githubusercontent.com/u/35647825?s=400&u=e79eecf030983c33e07c9a569bfd7f30b5547fe4&v=4  |
|  UE4中的Subsystem     |    https://www.cnblogs.com/yejianying/p/15029111.html      |    2021/07/19    |    Engine    |  Subsystem |   SRIN   |  BA3000  |    wubrightarmy@outlook.com     |     https://www.cnblogs.com/yejianying/      |  https://avatars.githubusercontent.com/u/35647825?s=400&u=e79eecf030983c33e07c9a569bfd7f30b5547fe4&v=4  |

**Comment by hxhb** [comment]
已添加 https://ue5wiki.com/contributor/SRIN/
