### ISSUE TITLE
外部文章收录

### ISSUE THREAD

**Issue by BA3000** [UnrealCommunity/commit_wiki#5]
| 文章名 | 文章链接 | 发表时间 | 分类(`/`分隔) | 标签(`/`分隔) | 作者名 | GithubID | Email | Website |AvatarLink |
|-------|----------|---------|--------------|---------------|-------|----------|-------|---------|-----------|
|    关于使用 Sequence Recorder 无法录制面部 Morph Target 问题的解决方法   |     https://www.cnblogs.com/yejianying/p/record_morph_target_with_ue4_sequence_recorder.html     |     2022-06-09 16:48    |     Animation         |      Animation/Plugins/Morph Target         |   SRIN    |      BA3000    |   wubrightarmy@outlook.com   |    https://www.cnblogs.com/yejianying/     |      https://avatars.githubusercontent.com/u/35647825?s=400&u=e79eecf030983c33e07c9a569bfd7f30b5547fe4&v=4     |

**Comment by hxhb** [comment]
已添加。
https://ue5wiki.com/contributor/SRIN/
